namespace AutoUpdaterModel;

/// <summary>
/// Embedded Ed25519 public key used to verify update packages.
/// Generated by AutoUpdaterReleaseTool init — replace the constant below
/// with the value printed by the tool, then rebuild.
/// </summary>
public static class PublicKey
{
    public const string Ed25519PublicKeyBase64 = "REPLACE_WITH_PUBLIC_KEY_FROM_RELEASE_TOOL";

    public static bool IsConfigured =>
        !string.IsNullOrWhiteSpace(Ed25519PublicKeyBase64) &&
        Ed25519PublicKeyBase64 != "REPLACE_WITH_PUBLIC_KEY_FROM_RELEASE_TOOL";

    public static byte[] Bytes
    {
        get
        {
            if (!IsConfigured)
                throw new InvalidOperationException(
                    "Ed25519 public key is not configured. Run AutoUpdaterReleaseTool init " +
                    "and paste the output into PublicKey.cs.");
            return Convert.FromBase64String(Ed25519PublicKeyBase64);
        }
    }
}
